// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: gitopia/gitopia/storage/events.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// EventProviderRegistered is emitted when a provider is registered
type EventProviderRegistered struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	PeerId  string `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
}

func (m *EventProviderRegistered) Reset()         { *m = EventProviderRegistered{} }
func (m *EventProviderRegistered) String() string { return proto.CompactTextString(m) }
func (*EventProviderRegistered) ProtoMessage()    {}
func (*EventProviderRegistered) Descriptor() ([]byte, []int) {
	return fileDescriptor_57683d92f491f563, []int{0}
}
func (m *EventProviderRegistered) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventProviderRegistered) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventProviderRegistered.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventProviderRegistered) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventProviderRegistered.Merge(m, src)
}
func (m *EventProviderRegistered) XXX_Size() int {
	return m.Size()
}
func (m *EventProviderRegistered) XXX_DiscardUnknown() {
	xxx_messageInfo_EventProviderRegistered.DiscardUnknown(m)
}

var xxx_messageInfo_EventProviderRegistered proto.InternalMessageInfo

func (m *EventProviderRegistered) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *EventProviderRegistered) GetPeerId() string {
	if m != nil {
		return m.PeerId
	}
	return ""
}

// EventProviderStatusUpdated is emitted when provider status is updated
type EventProviderStatusUpdated struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Online  bool   `protobuf:"varint,2,opt,name=online,proto3" json:"online,omitempty"`
}

func (m *EventProviderStatusUpdated) Reset()         { *m = EventProviderStatusUpdated{} }
func (m *EventProviderStatusUpdated) String() string { return proto.CompactTextString(m) }
func (*EventProviderStatusUpdated) ProtoMessage()    {}
func (*EventProviderStatusUpdated) Descriptor() ([]byte, []int) {
	return fileDescriptor_57683d92f491f563, []int{1}
}
func (m *EventProviderStatusUpdated) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventProviderStatusUpdated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventProviderStatusUpdated.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventProviderStatusUpdated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventProviderStatusUpdated.Merge(m, src)
}
func (m *EventProviderStatusUpdated) XXX_Size() int {
	return m.Size()
}
func (m *EventProviderStatusUpdated) XXX_DiscardUnknown() {
	xxx_messageInfo_EventProviderStatusUpdated.DiscardUnknown(m)
}

var xxx_messageInfo_EventProviderStatusUpdated proto.InternalMessageInfo

func (m *EventProviderStatusUpdated) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *EventProviderStatusUpdated) GetOnline() bool {
	if m != nil {
		return m.Online
	}
	return false
}

// EventPackfileUpdated is emitted when a packfile is updated
type EventPackfileUpdated struct {
	RepositoryId uint64 `protobuf:"varint,1,opt,name=repository_id,json=repositoryId,proto3" json:"repository_id,omitempty"`
	NewCid       string `protobuf:"bytes,2,opt,name=new_cid,json=newCid,proto3" json:"new_cid,omitempty"`
	OldCid       string `protobuf:"bytes,3,opt,name=old_cid,json=oldCid,proto3" json:"old_cid,omitempty"`
	NewName      string `protobuf:"bytes,4,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	OldName      string `protobuf:"bytes,5,opt,name=old_name,json=oldName,proto3" json:"old_name,omitempty"`
}

func (m *EventPackfileUpdated) Reset()         { *m = EventPackfileUpdated{} }
func (m *EventPackfileUpdated) String() string { return proto.CompactTextString(m) }
func (*EventPackfileUpdated) ProtoMessage()    {}
func (*EventPackfileUpdated) Descriptor() ([]byte, []int) {
	return fileDescriptor_57683d92f491f563, []int{2}
}
func (m *EventPackfileUpdated) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventPackfileUpdated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventPackfileUpdated.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventPackfileUpdated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventPackfileUpdated.Merge(m, src)
}
func (m *EventPackfileUpdated) XXX_Size() int {
	return m.Size()
}
func (m *EventPackfileUpdated) XXX_DiscardUnknown() {
	xxx_messageInfo_EventPackfileUpdated.DiscardUnknown(m)
}

var xxx_messageInfo_EventPackfileUpdated proto.InternalMessageInfo

func (m *EventPackfileUpdated) GetRepositoryId() uint64 {
	if m != nil {
		return m.RepositoryId
	}
	return 0
}

func (m *EventPackfileUpdated) GetNewCid() string {
	if m != nil {
		return m.NewCid
	}
	return ""
}

func (m *EventPackfileUpdated) GetOldCid() string {
	if m != nil {
		return m.OldCid
	}
	return ""
}

func (m *EventPackfileUpdated) GetNewName() string {
	if m != nil {
		return m.NewName
	}
	return ""
}

func (m *EventPackfileUpdated) GetOldName() string {
	if m != nil {
		return m.OldName
	}
	return ""
}

// EventReleaseAssetUpdated is emitted when a release asset is updated
type EventReleaseAssetUpdated struct {
	RepositoryId uint64 `protobuf:"varint,1,opt,name=repository_id,json=repositoryId,proto3" json:"repository_id,omitempty"`
	Tag          string `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Name         string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	NewCid       string `protobuf:"bytes,4,opt,name=new_cid,json=newCid,proto3" json:"new_cid,omitempty"`
	OldCid       string `protobuf:"bytes,5,opt,name=old_cid,json=oldCid,proto3" json:"old_cid,omitempty"`
	NewSha256    string `protobuf:"bytes,6,opt,name=new_sha256,json=newSha256,proto3" json:"new_sha256,omitempty"`
	OldSha256    string `protobuf:"bytes,7,opt,name=old_sha256,json=oldSha256,proto3" json:"old_sha256,omitempty"`
}

func (m *EventReleaseAssetUpdated) Reset()         { *m = EventReleaseAssetUpdated{} }
func (m *EventReleaseAssetUpdated) String() string { return proto.CompactTextString(m) }
func (*EventReleaseAssetUpdated) ProtoMessage()    {}
func (*EventReleaseAssetUpdated) Descriptor() ([]byte, []int) {
	return fileDescriptor_57683d92f491f563, []int{3}
}
func (m *EventReleaseAssetUpdated) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventReleaseAssetUpdated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventReleaseAssetUpdated.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventReleaseAssetUpdated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventReleaseAssetUpdated.Merge(m, src)
}
func (m *EventReleaseAssetUpdated) XXX_Size() int {
	return m.Size()
}
func (m *EventReleaseAssetUpdated) XXX_DiscardUnknown() {
	xxx_messageInfo_EventReleaseAssetUpdated.DiscardUnknown(m)
}

var xxx_messageInfo_EventReleaseAssetUpdated proto.InternalMessageInfo

func (m *EventReleaseAssetUpdated) GetRepositoryId() uint64 {
	if m != nil {
		return m.RepositoryId
	}
	return 0
}

func (m *EventReleaseAssetUpdated) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *EventReleaseAssetUpdated) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EventReleaseAssetUpdated) GetNewCid() string {
	if m != nil {
		return m.NewCid
	}
	return ""
}

func (m *EventReleaseAssetUpdated) GetOldCid() string {
	if m != nil {
		return m.OldCid
	}
	return ""
}

func (m *EventReleaseAssetUpdated) GetNewSha256() string {
	if m != nil {
		return m.NewSha256
	}
	return ""
}

func (m *EventReleaseAssetUpdated) GetOldSha256() string {
	if m != nil {
		return m.OldSha256
	}
	return ""
}

// EventChallengeCreated is emitted when a new challenge is created
type EventChallengeCreated struct {
	ChallengeId uint64 `protobuf:"varint,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	Provider    string `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
}

func (m *EventChallengeCreated) Reset()         { *m = EventChallengeCreated{} }
func (m *EventChallengeCreated) String() string { return proto.CompactTextString(m) }
func (*EventChallengeCreated) ProtoMessage()    {}
func (*EventChallengeCreated) Descriptor() ([]byte, []int) {
	return fileDescriptor_57683d92f491f563, []int{4}
}
func (m *EventChallengeCreated) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventChallengeCreated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventChallengeCreated.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventChallengeCreated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventChallengeCreated.Merge(m, src)
}
func (m *EventChallengeCreated) XXX_Size() int {
	return m.Size()
}
func (m *EventChallengeCreated) XXX_DiscardUnknown() {
	xxx_messageInfo_EventChallengeCreated.DiscardUnknown(m)
}

var xxx_messageInfo_EventChallengeCreated proto.InternalMessageInfo

func (m *EventChallengeCreated) GetChallengeId() uint64 {
	if m != nil {
		return m.ChallengeId
	}
	return 0
}

func (m *EventChallengeCreated) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

// EventChallengeCompleted is emitted when a challenge is completed
type EventChallengeCompleted struct {
	ChallengeId uint64 `protobuf:"varint,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	Provider    string `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Success     bool   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
}

func (m *EventChallengeCompleted) Reset()         { *m = EventChallengeCompleted{} }
func (m *EventChallengeCompleted) String() string { return proto.CompactTextString(m) }
func (*EventChallengeCompleted) ProtoMessage()    {}
func (*EventChallengeCompleted) Descriptor() ([]byte, []int) {
	return fileDescriptor_57683d92f491f563, []int{5}
}
func (m *EventChallengeCompleted) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventChallengeCompleted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventChallengeCompleted.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventChallengeCompleted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventChallengeCompleted.Merge(m, src)
}
func (m *EventChallengeCompleted) XXX_Size() int {
	return m.Size()
}
func (m *EventChallengeCompleted) XXX_DiscardUnknown() {
	xxx_messageInfo_EventChallengeCompleted.DiscardUnknown(m)
}

var xxx_messageInfo_EventChallengeCompleted proto.InternalMessageInfo

func (m *EventChallengeCompleted) GetChallengeId() uint64 {
	if m != nil {
		return m.ChallengeId
	}
	return 0
}

func (m *EventChallengeCompleted) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *EventChallengeCompleted) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

// EventProviderUnregistered is emitted when a provider initiates unregistration
type EventProviderUnregistered struct {
	Address               string    `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	UnstakeCompletionTime time.Time `protobuf:"bytes,2,opt,name=unstake_completion_time,json=unstakeCompletionTime,proto3,stdtime" json:"unstake_completion_time"`
}

func (m *EventProviderUnregistered) Reset()         { *m = EventProviderUnregistered{} }
func (m *EventProviderUnregistered) String() string { return proto.CompactTextString(m) }
func (*EventProviderUnregistered) ProtoMessage()    {}
func (*EventProviderUnregistered) Descriptor() ([]byte, []int) {
	return fileDescriptor_57683d92f491f563, []int{6}
}
func (m *EventProviderUnregistered) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventProviderUnregistered) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventProviderUnregistered.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventProviderUnregistered) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventProviderUnregistered.Merge(m, src)
}
func (m *EventProviderUnregistered) XXX_Size() int {
	return m.Size()
}
func (m *EventProviderUnregistered) XXX_DiscardUnknown() {
	xxx_messageInfo_EventProviderUnregistered.DiscardUnknown(m)
}

var xxx_messageInfo_EventProviderUnregistered proto.InternalMessageInfo

func (m *EventProviderUnregistered) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *EventProviderUnregistered) GetUnstakeCompletionTime() time.Time {
	if m != nil {
		return m.UnstakeCompletionTime
	}
	return time.Time{}
}

// EventProviderUnstakeCompleted is emitted when a provider's unstaking is completed
type EventProviderUnstakeCompleted struct {
	Address string     `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Amount  types.Coin `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount"`
}

func (m *EventProviderUnstakeCompleted) Reset()         { *m = EventProviderUnstakeCompleted{} }
func (m *EventProviderUnstakeCompleted) String() string { return proto.CompactTextString(m) }
func (*EventProviderUnstakeCompleted) ProtoMessage()    {}
func (*EventProviderUnstakeCompleted) Descriptor() ([]byte, []int) {
	return fileDescriptor_57683d92f491f563, []int{7}
}
func (m *EventProviderUnstakeCompleted) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventProviderUnstakeCompleted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventProviderUnstakeCompleted.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventProviderUnstakeCompleted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventProviderUnstakeCompleted.Merge(m, src)
}
func (m *EventProviderUnstakeCompleted) XXX_Size() int {
	return m.Size()
}
func (m *EventProviderUnstakeCompleted) XXX_DiscardUnknown() {
	xxx_messageInfo_EventProviderUnstakeCompleted.DiscardUnknown(m)
}

var xxx_messageInfo_EventProviderUnstakeCompleted proto.InternalMessageInfo

func (m *EventProviderUnstakeCompleted) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *EventProviderUnstakeCompleted) GetAmount() types.Coin {
	if m != nil {
		return m.Amount
	}
	return types.Coin{}
}

// EventMergePullRequest is emitted when a pull request is merged
type EventMergePullRequest struct {
	Creator         string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	PullRequestId   uint64 `protobuf:"varint,2,opt,name=pull_request_id,json=pullRequestId,proto3" json:"pull_request_id,omitempty"`
	PullRequestIid  uint64 `protobuf:"varint,3,opt,name=pull_request_iid,json=pullRequestIid,proto3" json:"pull_request_iid,omitempty"`
	State           string `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	MergeCommitSha  string `protobuf:"bytes,5,opt,name=merge_commit_sha,json=mergeCommitSha,proto3" json:"merge_commit_sha,omitempty"`
	TaskId          uint64 `protobuf:"varint,6,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskState       string `protobuf:"bytes,7,opt,name=task_state,json=taskState,proto3" json:"task_state,omitempty"`
	RepoName        string `protobuf:"bytes,8,opt,name=repo_name,json=repoName,proto3" json:"repo_name,omitempty"`
	RepoId          uint64 `protobuf:"varint,9,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	RepoOwnerId     string `protobuf:"bytes,10,opt,name=repo_owner_id,json=repoOwnerId,proto3" json:"repo_owner_id,omitempty"`
	RepoOwnerType   string `protobuf:"bytes,11,opt,name=repo_owner_type,json=repoOwnerType,proto3" json:"repo_owner_type,omitempty"`
	PullRequestHead string `protobuf:"bytes,14,opt,name=pull_request_head,json=pullRequestHead,proto3" json:"pull_request_head,omitempty"`
	RepoBranch      string `protobuf:"bytes,15,opt,name=repo_branch,json=repoBranch,proto3" json:"repo_branch,omitempty"`
	MergedBy        string `protobuf:"bytes,16,opt,name=merged_by,json=mergedBy,proto3" json:"merged_by,omitempty"`
	UpdatedAt       int64  `protobuf:"varint,17,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	MergedAt        int64  `protobuf:"varint,18,opt,name=merged_at,json=mergedAt,proto3" json:"merged_at,omitempty"`
}

func (m *EventMergePullRequest) Reset()         { *m = EventMergePullRequest{} }
func (m *EventMergePullRequest) String() string { return proto.CompactTextString(m) }
func (*EventMergePullRequest) ProtoMessage()    {}
func (*EventMergePullRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_57683d92f491f563, []int{8}
}
func (m *EventMergePullRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventMergePullRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventMergePullRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventMergePullRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventMergePullRequest.Merge(m, src)
}
func (m *EventMergePullRequest) XXX_Size() int {
	return m.Size()
}
func (m *EventMergePullRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EventMergePullRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EventMergePullRequest proto.InternalMessageInfo

func (m *EventMergePullRequest) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *EventMergePullRequest) GetPullRequestId() uint64 {
	if m != nil {
		return m.PullRequestId
	}
	return 0
}

func (m *EventMergePullRequest) GetPullRequestIid() uint64 {
	if m != nil {
		return m.PullRequestIid
	}
	return 0
}

func (m *EventMergePullRequest) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *EventMergePullRequest) GetMergeCommitSha() string {
	if m != nil {
		return m.MergeCommitSha
	}
	return ""
}

func (m *EventMergePullRequest) GetTaskId() uint64 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *EventMergePullRequest) GetTaskState() string {
	if m != nil {
		return m.TaskState
	}
	return ""
}

func (m *EventMergePullRequest) GetRepoName() string {
	if m != nil {
		return m.RepoName
	}
	return ""
}

func (m *EventMergePullRequest) GetRepoId() uint64 {
	if m != nil {
		return m.RepoId
	}
	return 0
}

func (m *EventMergePullRequest) GetRepoOwnerId() string {
	if m != nil {
		return m.RepoOwnerId
	}
	return ""
}

func (m *EventMergePullRequest) GetRepoOwnerType() string {
	if m != nil {
		return m.RepoOwnerType
	}
	return ""
}

func (m *EventMergePullRequest) GetPullRequestHead() string {
	if m != nil {
		return m.PullRequestHead
	}
	return ""
}

func (m *EventMergePullRequest) GetRepoBranch() string {
	if m != nil {
		return m.RepoBranch
	}
	return ""
}

func (m *EventMergePullRequest) GetMergedBy() string {
	if m != nil {
		return m.MergedBy
	}
	return ""
}

func (m *EventMergePullRequest) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *EventMergePullRequest) GetMergedAt() int64 {
	if m != nil {
		return m.MergedAt
	}
	return 0
}

func init() {
	proto.RegisterType((*EventProviderRegistered)(nil), "gitopia.gitopia.storage.EventProviderRegistered")
	proto.RegisterType((*EventProviderStatusUpdated)(nil), "gitopia.gitopia.storage.EventProviderStatusUpdated")
	proto.RegisterType((*EventPackfileUpdated)(nil), "gitopia.gitopia.storage.EventPackfileUpdated")
	proto.RegisterType((*EventReleaseAssetUpdated)(nil), "gitopia.gitopia.storage.EventReleaseAssetUpdated")
	proto.RegisterType((*EventChallengeCreated)(nil), "gitopia.gitopia.storage.EventChallengeCreated")
	proto.RegisterType((*EventChallengeCompleted)(nil), "gitopia.gitopia.storage.EventChallengeCompleted")
	proto.RegisterType((*EventProviderUnregistered)(nil), "gitopia.gitopia.storage.EventProviderUnregistered")
	proto.RegisterType((*EventProviderUnstakeCompleted)(nil), "gitopia.gitopia.storage.EventProviderUnstakeCompleted")
	proto.RegisterType((*EventMergePullRequest)(nil), "gitopia.gitopia.storage.EventMergePullRequest")
}

func init() {
	proto.RegisterFile("gitopia/gitopia/storage/events.proto", fileDescriptor_57683d92f491f563)
}

var fileDescriptor_57683d92f491f563 = []byte{
	// 863 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xdd, 0x6e, 0xdc, 0x44,
	0x14, 0x8e, 0xc9, 0x76, 0xb3, 0x3b, 0x69, 0x7e, 0x6a, 0xa5, 0xc4, 0x59, 0xd4, 0x4d, 0x31, 0x08,
	0x45, 0x48, 0xd8, 0x6a, 0x11, 0xe5, 0x3a, 0xbb, 0x42, 0xb0, 0x12, 0x84, 0xca, 0x69, 0xb9, 0x40,
	0x48, 0xd6, 0xac, 0xe7, 0xd4, 0x6b, 0xc5, 0x9e, 0x31, 0x33, 0xe3, 0x2c, 0xfb, 0x16, 0x95, 0x78,
	0x84, 0xbe, 0x4c, 0x2f, 0x7b, 0x83, 0xc4, 0x15, 0xa0, 0xe4, 0x45, 0xd0, 0x99, 0x19, 0xef, 0x4f,
	0x25, 0x2a, 0x10, 0x57, 0x9e, 0x73, 0xbe, 0xf3, 0xf3, 0x9d, 0xf1, 0xf9, 0x6c, 0xf2, 0x71, 0x5e,
	0x68, 0x51, 0x17, 0x34, 0x6e, 0x9f, 0x4a, 0x0b, 0x49, 0x73, 0x88, 0xe1, 0x1a, 0xb8, 0x56, 0x51,
	0x2d, 0x85, 0x16, 0xfe, 0xb1, 0x43, 0xa3, 0xf6, 0xe9, 0xa2, 0x06, 0xa7, 0xb9, 0x10, 0x79, 0x09,
	0xb1, 0x09, 0x9b, 0x36, 0x2f, 0x62, 0x5d, 0x54, 0xa0, 0x34, 0xad, 0x6a, 0x9b, 0x39, 0x38, 0xca,
	0x45, 0x2e, 0xcc, 0x31, 0xc6, 0x93, 0xf3, 0x0e, 0x33, 0xa1, 0x2a, 0xa1, 0xe2, 0x29, 0x55, 0x10,
	0x5f, 0x3f, 0x9a, 0x82, 0xa6, 0x8f, 0xe2, 0x4c, 0x14, 0xdc, 0xe2, 0xe1, 0xb7, 0xe4, 0xf8, 0x2b,
	0xec, 0xff, 0x54, 0x8a, 0xeb, 0x82, 0x81, 0x4c, 0x20, 0x2f, 0x94, 0x06, 0x09, 0xcc, 0x0f, 0xc8,
	0x0e, 0x65, 0x4c, 0x82, 0x52, 0x81, 0xf7, 0xd0, 0x3b, 0xeb, 0x27, 0xad, 0xe9, 0x1f, 0x93, 0x9d,
	0x1a, 0x40, 0xa6, 0x05, 0x0b, 0xde, 0x33, 0x48, 0x17, 0xcd, 0x09, 0x0b, 0x2f, 0xc8, 0x60, 0xa3,
	0xda, 0xa5, 0xa6, 0xba, 0x51, 0xcf, 0x6b, 0x46, 0xf5, 0x3b, 0x0b, 0xbe, 0x4f, 0xba, 0x82, 0x97,
	0x05, 0x07, 0x53, 0xaf, 0x97, 0x38, 0x2b, 0x7c, 0xe5, 0x91, 0x23, 0x5b, 0x90, 0x66, 0x57, 0x2f,
	0x8a, 0x12, 0xda, 0x52, 0x1f, 0x91, 0x3d, 0x09, 0xb5, 0x50, 0x85, 0x16, 0x72, 0x81, 0x3c, 0xb0,
	0x60, 0x27, 0xb9, 0xbb, 0x72, 0x4e, 0x18, 0xd2, 0xe4, 0x30, 0x4f, 0xb3, 0x15, 0x4d, 0x0e, 0xf3,
	0x71, 0x61, 0x00, 0x51, 0x32, 0x03, 0x6c, 0x5b, 0x40, 0x94, 0x0c, 0x81, 0x13, 0xd2, 0xc3, 0x0c,
	0x4e, 0x2b, 0x08, 0x3a, 0x96, 0x22, 0x87, 0xf9, 0x05, 0xad, 0x00, 0x21, 0xcc, 0x31, 0xd0, 0x1d,
	0x0b, 0x89, 0x92, 0x21, 0x14, 0xfe, 0xe6, 0x91, 0xc0, 0xb0, 0x4c, 0xa0, 0x04, 0xaa, 0xe0, 0x5c,
	0x29, 0xd0, 0xff, 0x89, 0xe9, 0x21, 0xd9, 0xd6, 0x34, 0x77, 0x2c, 0xf1, 0xe8, 0xfb, 0xa4, 0x63,
	0x5a, 0x59, 0x7e, 0xe6, 0xbc, 0x3e, 0x4f, 0xe7, 0x9f, 0xe6, 0xb9, 0xb3, 0x31, 0xcf, 0x03, 0x42,
	0x30, 0x43, 0xcd, 0xe8, 0xe3, 0x2f, 0x9e, 0x04, 0x5d, 0x83, 0xf5, 0x39, 0xcc, 0x2f, 0x8d, 0x03,
	0x61, 0xcc, 0x73, 0xf0, 0x8e, 0x85, 0x45, 0xc9, 0x2c, 0x1c, 0xfe, 0x40, 0xee, 0x9b, 0xb1, 0xc6,
	0x33, 0x5a, 0x96, 0xc0, 0x73, 0x18, 0x4b, 0x30, 0x33, 0x7d, 0x48, 0xee, 0x66, 0xad, 0x6f, 0x35,
	0xd2, 0xee, 0xd2, 0x37, 0x61, 0xfe, 0x80, 0xf4, 0x6a, 0xb7, 0x04, 0x6e, 0xac, 0xa5, 0x1d, 0x4a,
	0xb7, 0x73, 0xab, 0xba, 0xa2, 0xaa, 0x4b, 0xf8, 0xff, 0x95, 0x71, 0xc3, 0x54, 0x93, 0x65, 0xb8,
	0x61, 0xdb, 0x66, 0x91, 0x5a, 0x33, 0xfc, 0xd5, 0x23, 0x27, 0x1b, 0xab, 0xf9, 0x9c, 0xcb, 0x7f,
	0xb3, 0xea, 0x3f, 0x91, 0xe3, 0x86, 0x2b, 0x4d, 0xaf, 0x20, 0xcd, 0x2c, 0xcb, 0x42, 0xf0, 0x14,
	0xb5, 0x67, 0x9a, 0xef, 0x3e, 0x1e, 0x44, 0x56, 0x98, 0x51, 0x2b, 0xcc, 0xe8, 0x59, 0x2b, 0xcc,
	0x51, 0xef, 0xf5, 0x1f, 0xa7, 0x5b, 0x2f, 0xff, 0x3c, 0xf5, 0x92, 0xfb, 0xae, 0xc8, 0x78, 0x59,
	0x03, 0xa3, 0x42, 0x49, 0x1e, 0xbc, 0x45, 0x6a, 0x3d, 0xea, 0x9d, 0xc4, 0xbe, 0x24, 0x5d, 0x5a,
	0x89, 0x86, 0x6b, 0xc7, 0xe3, 0x24, 0xb2, 0x4a, 0x8f, 0x50, 0xe9, 0x91, 0x53, 0x7a, 0x34, 0x16,
	0x05, 0x1f, 0x75, 0x90, 0x46, 0xe2, 0xc2, 0xc3, 0x57, 0x1d, 0xf7, 0x5a, 0xbf, 0x03, 0x99, 0xc3,
	0xd3, 0xa6, 0x2c, 0x13, 0xf8, 0xb9, 0x01, 0xa5, 0xb1, 0x59, 0x86, 0x6f, 0x58, 0xc8, 0xb6, 0x99,
	0x33, 0xfd, 0x4f, 0xc8, 0x41, 0xdd, 0x94, 0x65, 0x2a, 0x6d, 0x64, 0x2b, 0xfc, 0x4e, 0xb2, 0x57,
	0xaf, 0xf2, 0x27, 0xcc, 0x3f, 0x23, 0x87, 0x9b, 0x71, 0x4e, 0x61, 0x9d, 0x64, 0x7f, 0x3d, 0xb0,
	0x60, 0xfe, 0x11, 0xb9, 0xa3, 0x34, 0xd5, 0xad, 0xcc, 0xac, 0x81, 0xf9, 0x15, 0xb2, 0xc2, 0xbb,
	0xae, 0x0a, 0x8d, 0x9b, 0xe9, 0x36, 0x7a, 0xdf, 0xf8, 0xc7, 0xc6, 0x7d, 0x39, 0xa3, 0xb8, 0xf2,
	0x9a, 0xaa, 0x2b, 0x64, 0xd2, 0x35, 0x0d, 0xba, 0x68, 0x4e, 0xcc, 0xca, 0x1b, 0xc0, 0x56, 0x77,
	0x3b, 0x8d, 0x9e, 0x4b, 0xd3, 0xe1, 0x03, 0xd2, 0x47, 0xe5, 0x59, 0x1d, 0xf7, 0xec, 0xfa, 0xa0,
	0xe3, 0xc2, 0x09, 0xcc, 0x80, 0x05, 0x0b, 0xfa, 0xb6, 0x28, 0x9a, 0x13, 0xe6, 0x87, 0x56, 0xc4,
	0xa9, 0x98, 0x73, 0xfb, 0xd9, 0x23, 0x26, 0x73, 0x17, 0x9d, 0xdf, 0xa3, 0x6f, 0xc2, 0xf0, 0x8e,
	0xd6, 0x62, 0xf4, 0xa2, 0x86, 0x60, 0xd7, 0x44, 0xed, 0x2d, 0xa3, 0x9e, 0x2d, 0x6a, 0xf0, 0x3f,
	0x25, 0xf7, 0x36, 0xee, 0x68, 0x06, 0x94, 0x05, 0xfb, 0x26, 0xf2, 0x60, 0xed, 0x92, 0xbe, 0x01,
	0xca, 0xfc, 0x53, 0x62, 0x5a, 0xa4, 0x53, 0x49, 0x79, 0x36, 0x0b, 0x0e, 0x4c, 0x14, 0x41, 0xd7,
	0xc8, 0x78, 0x70, 0x1c, 0x73, 0x31, 0x2c, 0x9d, 0x2e, 0x82, 0x43, 0x3b, 0x8e, 0x75, 0x8c, 0x16,
	0x78, 0x15, 0x8d, 0xfd, 0x0a, 0xa5, 0x54, 0x07, 0xf7, 0x1e, 0x7a, 0x67, 0xdb, 0x49, 0xdf, 0x79,
	0xce, 0xf5, 0x5a, 0x2e, 0xd5, 0x81, 0x6f, 0x50, 0x97, 0x7b, 0xae, 0x47, 0x5f, 0xbf, 0xbe, 0x19,
	0x7a, 0x6f, 0x6e, 0x86, 0xde, 0x5f, 0x37, 0x43, 0xef, 0xe5, 0xed, 0x70, 0xeb, 0xcd, 0xed, 0x70,
	0xeb, 0xf7, 0xdb, 0xe1, 0xd6, 0x8f, 0x9f, 0xe5, 0x85, 0x9e, 0x35, 0xd3, 0x28, 0x13, 0x55, 0xfc,
	0xf6, 0x2f, 0xed, 0xfa, 0x49, 0xfc, 0xcb, 0xf2, 0xbf, 0x86, 0x57, 0xa0, 0xa6, 0x5d, 0xa3, 0x8b,
	0xcf, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xc3, 0x04, 0xc3, 0x22, 0xff, 0x06, 0x00, 0x00,
}

func (m *EventProviderRegistered) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventProviderRegistered) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventProviderRegistered) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PeerId) > 0 {
		i -= len(m.PeerId)
		copy(dAtA[i:], m.PeerId)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.PeerId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventProviderStatusUpdated) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventProviderStatusUpdated) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventProviderStatusUpdated) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Online {
		i--
		if m.Online {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventPackfileUpdated) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventPackfileUpdated) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventPackfileUpdated) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.OldName) > 0 {
		i -= len(m.OldName)
		copy(dAtA[i:], m.OldName)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.OldName)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.NewName) > 0 {
		i -= len(m.NewName)
		copy(dAtA[i:], m.NewName)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.NewName)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.OldCid) > 0 {
		i -= len(m.OldCid)
		copy(dAtA[i:], m.OldCid)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.OldCid)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.NewCid) > 0 {
		i -= len(m.NewCid)
		copy(dAtA[i:], m.NewCid)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.NewCid)))
		i--
		dAtA[i] = 0x12
	}
	if m.RepositoryId != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.RepositoryId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *EventReleaseAssetUpdated) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventReleaseAssetUpdated) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventReleaseAssetUpdated) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.OldSha256) > 0 {
		i -= len(m.OldSha256)
		copy(dAtA[i:], m.OldSha256)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.OldSha256)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.NewSha256) > 0 {
		i -= len(m.NewSha256)
		copy(dAtA[i:], m.NewSha256)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.NewSha256)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.OldCid) > 0 {
		i -= len(m.OldCid)
		copy(dAtA[i:], m.OldCid)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.OldCid)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.NewCid) > 0 {
		i -= len(m.NewCid)
		copy(dAtA[i:], m.NewCid)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.NewCid)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Tag) > 0 {
		i -= len(m.Tag)
		copy(dAtA[i:], m.Tag)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Tag)))
		i--
		dAtA[i] = 0x12
	}
	if m.RepositoryId != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.RepositoryId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *EventChallengeCreated) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventChallengeCreated) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventChallengeCreated) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Provider) > 0 {
		i -= len(m.Provider)
		copy(dAtA[i:], m.Provider)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Provider)))
		i--
		dAtA[i] = 0x12
	}
	if m.ChallengeId != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.ChallengeId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *EventChallengeCompleted) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventChallengeCompleted) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventChallengeCompleted) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Success {
		i--
		if m.Success {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if len(m.Provider) > 0 {
		i -= len(m.Provider)
		copy(dAtA[i:], m.Provider)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Provider)))
		i--
		dAtA[i] = 0x12
	}
	if m.ChallengeId != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.ChallengeId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *EventProviderUnregistered) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventProviderUnregistered) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventProviderUnregistered) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.UnstakeCompletionTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.UnstakeCompletionTime):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintEvents(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x12
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventProviderUnstakeCompleted) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventProviderUnstakeCompleted) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventProviderUnstakeCompleted) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventMergePullRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventMergePullRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventMergePullRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MergedAt != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.MergedAt))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x90
	}
	if m.UpdatedAt != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.UpdatedAt))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x88
	}
	if len(m.MergedBy) > 0 {
		i -= len(m.MergedBy)
		copy(dAtA[i:], m.MergedBy)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.MergedBy)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x82
	}
	if len(m.RepoBranch) > 0 {
		i -= len(m.RepoBranch)
		copy(dAtA[i:], m.RepoBranch)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.RepoBranch)))
		i--
		dAtA[i] = 0x7a
	}
	if len(m.PullRequestHead) > 0 {
		i -= len(m.PullRequestHead)
		copy(dAtA[i:], m.PullRequestHead)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.PullRequestHead)))
		i--
		dAtA[i] = 0x72
	}
	if len(m.RepoOwnerType) > 0 {
		i -= len(m.RepoOwnerType)
		copy(dAtA[i:], m.RepoOwnerType)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.RepoOwnerType)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.RepoOwnerId) > 0 {
		i -= len(m.RepoOwnerId)
		copy(dAtA[i:], m.RepoOwnerId)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.RepoOwnerId)))
		i--
		dAtA[i] = 0x52
	}
	if m.RepoId != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.RepoId))
		i--
		dAtA[i] = 0x48
	}
	if len(m.RepoName) > 0 {
		i -= len(m.RepoName)
		copy(dAtA[i:], m.RepoName)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.RepoName)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.TaskState) > 0 {
		i -= len(m.TaskState)
		copy(dAtA[i:], m.TaskState)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.TaskState)))
		i--
		dAtA[i] = 0x3a
	}
	if m.TaskId != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.TaskId))
		i--
		dAtA[i] = 0x30
	}
	if len(m.MergeCommitSha) > 0 {
		i -= len(m.MergeCommitSha)
		copy(dAtA[i:], m.MergeCommitSha)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.MergeCommitSha)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.State) > 0 {
		i -= len(m.State)
		copy(dAtA[i:], m.State)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.State)))
		i--
		dAtA[i] = 0x22
	}
	if m.PullRequestIid != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.PullRequestIid))
		i--
		dAtA[i] = 0x18
	}
	if m.PullRequestId != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.PullRequestId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintEvents(dAtA []byte, offset int, v uint64) int {
	offset -= sovEvents(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EventProviderRegistered) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.PeerId)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func (m *EventProviderStatusUpdated) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	if m.Online {
		n += 2
	}
	return n
}

func (m *EventPackfileUpdated) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RepositoryId != 0 {
		n += 1 + sovEvents(uint64(m.RepositoryId))
	}
	l = len(m.NewCid)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.OldCid)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.NewName)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.OldName)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func (m *EventReleaseAssetUpdated) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RepositoryId != 0 {
		n += 1 + sovEvents(uint64(m.RepositoryId))
	}
	l = len(m.Tag)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.NewCid)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.OldCid)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.NewSha256)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.OldSha256)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func (m *EventChallengeCreated) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ChallengeId != 0 {
		n += 1 + sovEvents(uint64(m.ChallengeId))
	}
	l = len(m.Provider)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func (m *EventChallengeCompleted) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ChallengeId != 0 {
		n += 1 + sovEvents(uint64(m.ChallengeId))
	}
	l = len(m.Provider)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	if m.Success {
		n += 2
	}
	return n
}

func (m *EventProviderUnregistered) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.UnstakeCompletionTime)
	n += 1 + l + sovEvents(uint64(l))
	return n
}

func (m *EventProviderUnstakeCompleted) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovEvents(uint64(l))
	return n
}

func (m *EventMergePullRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	if m.PullRequestId != 0 {
		n += 1 + sovEvents(uint64(m.PullRequestId))
	}
	if m.PullRequestIid != 0 {
		n += 1 + sovEvents(uint64(m.PullRequestIid))
	}
	l = len(m.State)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.MergeCommitSha)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	if m.TaskId != 0 {
		n += 1 + sovEvents(uint64(m.TaskId))
	}
	l = len(m.TaskState)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.RepoName)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	if m.RepoId != 0 {
		n += 1 + sovEvents(uint64(m.RepoId))
	}
	l = len(m.RepoOwnerId)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.RepoOwnerType)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.PullRequestHead)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.RepoBranch)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.MergedBy)
	if l > 0 {
		n += 2 + l + sovEvents(uint64(l))
	}
	if m.UpdatedAt != 0 {
		n += 2 + sovEvents(uint64(m.UpdatedAt))
	}
	if m.MergedAt != 0 {
		n += 2 + sovEvents(uint64(m.MergedAt))
	}
	return n
}

func sovEvents(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEvents(x uint64) (n int) {
	return sovEvents(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EventProviderRegistered) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventProviderRegistered: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventProviderRegistered: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PeerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PeerId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventProviderStatusUpdated) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventProviderStatusUpdated: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventProviderStatusUpdated: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Online", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Online = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventPackfileUpdated) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventPackfileUpdated: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventPackfileUpdated: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RepositoryId", wireType)
			}
			m.RepositoryId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RepositoryId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewCid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewCid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OldCid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OldCid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OldName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OldName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventReleaseAssetUpdated) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventReleaseAssetUpdated: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventReleaseAssetUpdated: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RepositoryId", wireType)
			}
			m.RepositoryId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RepositoryId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tag", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tag = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewCid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewCid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OldCid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OldCid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewSha256", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewSha256 = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OldSha256", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OldSha256 = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventChallengeCreated) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventChallengeCreated: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventChallengeCreated: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChallengeId", wireType)
			}
			m.ChallengeId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChallengeId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Provider", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Provider = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventChallengeCompleted) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventChallengeCompleted: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventChallengeCompleted: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChallengeId", wireType)
			}
			m.ChallengeId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChallengeId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Provider", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Provider = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Success", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Success = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventProviderUnregistered) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventProviderUnregistered: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventProviderUnregistered: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnstakeCompletionTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.UnstakeCompletionTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventProviderUnstakeCompleted) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventProviderUnstakeCompleted: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventProviderUnstakeCompleted: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventMergePullRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventMergePullRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventMergePullRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PullRequestId", wireType)
			}
			m.PullRequestId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PullRequestId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PullRequestIid", wireType)
			}
			m.PullRequestIid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PullRequestIid |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.State = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MergeCommitSha", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MergeCommitSha = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskId", wireType)
			}
			m.TaskId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TaskId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskState", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TaskState = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RepoName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RepoName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RepoId", wireType)
			}
			m.RepoId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RepoId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RepoOwnerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RepoOwnerId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RepoOwnerType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RepoOwnerType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PullRequestHead", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PullRequestHead = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RepoBranch", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RepoBranch = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MergedBy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MergedBy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAt", wireType)
			}
			m.UpdatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 18:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MergedAt", wireType)
			}
			m.MergedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MergedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvents(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEvents
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEvents
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEvents
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEvents        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvents          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEvents = fmt.Errorf("proto: unexpected end of group")
)
