package types

var ReservedUsernames = map[string]string{
	"400":                        "HTTP response status code",
	"401":                        "HTTP response status code",
	"402":                        "HTTP response status code",
	"403":                        "HTTP response status code",
	"404":                        "HTTP response status code",
	"405":                        "HTTP response status code",
	"406":                        "HTTP response status code",
	"407":                        "HTTP response status code",
	"408":                        "HTTP response status code",
	"409":                        "HTTP response status code",
	"410":                        "HTTP response status code",
	"411":                        "HTTP response status code",
	"412":                        "HTTP response status code",
	"413":                        "HTTP response status code",
	"414":                        "HTTP response status code",
	"415":                        "HTTP response status code",
	"416":                        "HTTP response status code",
	"417":                        "HTTP response status code",
	"418":                        "HTTP response status code",
	"419":                        "HTTP response status code",
	"420":                        "HTTP response status code",
	"421":                        "HTTP response status code",
	"422":                        "HTTP response status code",
	"423":                        "HTTP response status code",
	"424":                        "HTTP response status code",
	"425":                        "HTTP response status code",
	"426":                        "HTTP response status code",
	"427":                        "HTTP response status code",
	"428":                        "HTTP response status code",
	"429":                        "HTTP response status code",
	"430":                        "HTTP response status code",
	"431":                        "HTTP response status code",
	"500":                        "HTTP response status code",
	"501":                        "HTTP response status code",
	"502":                        "HTTP response status code",
	"503":                        "HTTP response status code",
	"504":                        "HTTP response status code",
	"505":                        "HTTP response status code",
	"506":                        "HTTP response status code",
	"507":                        "HTTP response status code",
	"508":                        "HTTP response status code",
	"509":                        "HTTP response status code",
	"510":                        "HTTP response status code",
	"511":                        "HTTP response status code",
	"about":                      "About Page",
	"access":                     "",
	"account":                    "",
	"admin":                      "",
	"advisories":                 "",
	"anonymous":                  "",
	"any":                        "",
	"api":                        "",
	"apps":                       "",
	"assets":                     "",
	"attributes":                 "",
	"auth":                       "",
	"authz":                      "",
	"bank":                       "",
	"billing":                    "",
	"blob":                       "",
	"blog":                       "",
	"bounties":                   "",
	"bounty":                     "",
	"branches":                   "",
	"brand-assets":               "",
	"business":                   "",
	"businesses":                 "",
	"cache":                      "",
	"case-studies":               "",
	"categories":                 "",
	"central":                    "",
	"certification":              "",
	"changelog":                  "",
	"cla":                        "Contributor License Agreement",
	"cloud":                      "",
	"codereview":                 "",
	"collection":                 "",
	"collections":                "",
	"comments":                   "",
	"commit":                     "",
	"commits":                    "",
	"community":                  "",
	"companies":                  "",
	"company":                    "",
	"compare":                    "",
	"consensus":                  "",
	"contact":                    "",
	"contacts":                   "",
	"contributing":               "",
	"cookbook":                   "",
	"crypto":                     "",
	"customer-stories":           "",
	"customer":                   "",
	"customers":                  "",
	"dashboard":                  "",
	"dashboards":                 "",
	"design":                     "",
	"develop":                    "",
	"developer":                  "",
	"diff":                       "",
	"discover":                   "",
	"discussions":                "",
	"distribution":               "",
	"docs":                       "",
	"downloads":                  "",
	"downtime":                   "",
	"editor":                     "",
	"editors":                    "",
	"edu":                        "",
	"enterprise":                 "",
	"events":                     "",
	"explore":                    "",
	"explorer":                   "",
	"featured":                   "",
	"features":                   "",
	"files":                      "",
	"forked":                     "",
	"forum":                      "",
	"garage":                     "",
	"ghost":                      "",
	"gitopiaseasonofblockchains": "",
	"gov":                        "",
	"governance":                 "",
	"graphs":                     "",
	"gsob":                       "",
	"guide":                      "",
	"guides":                     "",
	"hackathon":                  "",
	"help":                       "",
	"help-wanted":                "",
	"home":                       "",
	"hooks":                      "",
	"hosting":                    "",
	"images":                     "",
	"inbox":                      "",
	"individual":                 "",
	"info":                       "",
	"integration":                "",
	"interfaces":                 "",
	"introduction":               "",
	"invalid-email-address":      "",
	"investors":                  "",
	"issues":                     "",
	"jobs":                       "",
	"join":                       "",
	"journal":                    "",
	"journals":                   "",
	"lab":                        "",
	"labs":                       "",
	"languages":                  "",
	"launch":                     "",
	"layouts":                    "",
	"learn":                      "",
	"legal":                      "",
	"library":                    "",
	"linux":                      "",
	"listings":                   "",
	"lists":                      "",
	"login":                      "",
	"logos":                      "",
	"logout":                     "",
	"mac":                        "",
	"maintenance":                "",
	"malware":                    "",
	"man":                        "",
	"marketplace":                "",
	"mention":                    "",
	"mentioned":                  "",
	"mentioning":                 "",
	"mentions":                   "",
	"migrating":                  "",
	"milestones":                 "",
	"mine":                       "",
	"mint":                       "",
	"mirrors":                    "",
	"mobile":                     "",
	"navigation":                 "",
	"network":                    "",
	"nerd":                       "",
	"nerds":                      "",
	"nerdz":                      "",
	"new":                        "",
	"news":                       "",
	"nft":                        "NFT Page",
	"nfts":                       "NFT Page",
	"none":                       "",
	"nonprofit":                  "",
	"nonprofits":                 "",
	"notices":                    "",
	"notifications":              "",
	"oauth":                      "",
	"offer":                      "",
	"open-source":                "",
	"organisations":              "",
	"organizations":              "",
	"orgs":                       "",
	"pages":                      "",
	"partners":                   "",
	"payments":                   "",
	"personal":                   "",
	"plans":                      "",
	"plugins":                    "",
	"popular":                    "",
	"popularity":                 "",
	"posts":                      "",
	"press":                      "",
	"professional":               "",
	"projects":                   "",
	"proposal":                   "",
	"proposals":                  "",
	"pulls":                      "",
	"raw":                        "",
	"readme":                     "",
	"recommendations":            "",
	"redeem":                     "",
	"relayer":                    "",
	"relayers":                   "",
	"releases":                   "",
	"render":                     "",
	"reply":                      "",
	"repositories":               "",
	"resources":                  "",
	"restore":                    "",
	"revert":                     "",
	"saved":                      "",
	"scraping":                   "",
	"search":                     "",
	"security":                   "",
	"services":                   "",
	"sessions":                   "",
	"settings":                   "",
	"shareholders":               "",
	"shop":                       "",
	"showcases":                  "",
	"signin":                     "",
	"signup":                     "",
	"site":                       "",
	"spam":                       "",
	"sponsors":                   "",
	"ssh":                        "",
	"staff":                      "",
	"staking":                    "",
	"starred":                    "",
	"stars":                      "",
	"static":                     "",
	"status":                     "",
	"statuses":                   "",
	"storage":                    "",
	"store":                      "",
	"stories":                    "",
	"styleguide":                 "",
	"subscriptions":              "",
	"suggest":                    "",
	"suggestion":                 "",
	"suggestions":                "",
	"support":                    "",
	"suspended":                  "",
	"talks":                      "",
	"team":                       "",
	"teams":                      "",
	"terms":                      "",
	"terms-of-service":           "",
	"timeline":                   "",
	"token":                      "",
	"tokens":                     "",
	"topic":                      "",
	"topics":                     "",
	"tos":                        "",
	"tour":                       "",
	"translations":               "",
	"tree":                       "",
	"trending":                   "",
	"updates":                    "",
	"upgrade":                    "",
	"upgrades":                   "",
	"username":                   "",
	"users":                      "",
	"validators":                 "",
	"visualization":              "",
	"vote":                       "",
	"watching":                   "",
	"wiki":                       "",
	"works-with":                 "",
	"www0":                       "",
	"www1":                       "",
	"www2":                       "",
	"www3":                       "",
	"www4":                       "",
	"www5":                       "",
	"www6":                       "",
	"www7":                       "",
	"www8":                       "",
	"www9":                       "",
}
