// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rewards/params.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type RewardSeries struct {
	Series     int32                                    `protobuf:"varint,1,opt,name=series,proto3" json:"series,omitempty" yaml:"series"`
	RewardPool github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,2,rep,name=reward_pool,json=rewardPool,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"reward_pool" yaml:"reward_pool"`
}

func (m *RewardSeries) Reset()         { *m = RewardSeries{} }
func (m *RewardSeries) String() string { return proto.CompactTextString(m) }
func (*RewardSeries) ProtoMessage()    {}
func (*RewardSeries) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4f6e2be212d3b23, []int{0}
}
func (m *RewardSeries) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RewardSeries) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RewardSeries.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RewardSeries) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RewardSeries.Merge(m, src)
}
func (m *RewardSeries) XXX_Size() int {
	return m.Size()
}
func (m *RewardSeries) XXX_DiscardUnknown() {
	xxx_messageInfo_RewardSeries.DiscardUnknown(m)
}

var xxx_messageInfo_RewardSeries proto.InternalMessageInfo

func (m *RewardSeries) GetSeries() int32 {
	if m != nil {
		return m.Series
	}
	return 0
}

func (m *RewardSeries) GetRewardPool() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.RewardPool
	}
	return nil
}

// Params defines the parameters for the module.
type Params struct {
	EvaluatorAddress string          `protobuf:"bytes,1,opt,name=evaluator_address,json=evaluatorAddress,proto3" json:"evaluator_address,omitempty" yaml:"evaluator_address"`
	RewardSeries     []*RewardSeries `protobuf:"bytes,2,rep,name=reward_series,json=rewardSeries,proto3" json:"reward_series,omitempty" yaml:"reward_series"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4f6e2be212d3b23, []int{1}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetEvaluatorAddress() string {
	if m != nil {
		return m.EvaluatorAddress
	}
	return ""
}

func (m *Params) GetRewardSeries() []*RewardSeries {
	if m != nil {
		return m.RewardSeries
	}
	return nil
}

func init() {
	proto.RegisterType((*RewardSeries)(nil), "gitopia.gitopia.rewards.RewardSeries")
	proto.RegisterType((*Params)(nil), "gitopia.gitopia.rewards.Params")
}

func init() { proto.RegisterFile("rewards/params.proto", fileDescriptor_d4f6e2be212d3b23) }

var fileDescriptor_d4f6e2be212d3b23 = []byte{
	// 362 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xb3, 0x8a, 0x05, 0xb7, 0x2d, 0xd8, 0x50, 0x30, 0x16, 0x49, 0x4a, 0x40, 0xa8, 0x82,
	0xbb, 0x54, 0x6f, 0xde, 0x8c, 0x22, 0x78, 0x2b, 0xf1, 0xe6, 0xa5, 0x6c, 0x9a, 0x25, 0x06, 0x9b,
	0x6e, 0xd8, 0x4d, 0xab, 0xbd, 0xfa, 0x04, 0x3e, 0x87, 0x6f, 0xe0, 0xc5, 0x73, 0x8f, 0x3d, 0x7a,
	0x8a, 0xd2, 0xbe, 0x41, 0x9e, 0x40, 0xba, 0xbb, 0x2d, 0x11, 0xf1, 0x34, 0xc3, 0xe4, 0x9f, 0xf9,
	0x67, 0xbe, 0x2c, 0x6c, 0x72, 0xfa, 0x44, 0x78, 0x28, 0x70, 0x4a, 0x38, 0x49, 0x04, 0x4a, 0x39,
	0xcb, 0x98, 0xb9, 0x1f, 0xc5, 0x19, 0x4b, 0x63, 0x82, 0xd6, 0x51, 0xab, 0x5a, 0xcd, 0x88, 0x45,
	0x4c, 0x6a, 0xf0, 0x2a, 0x53, 0xf2, 0x96, 0x3d, 0x60, 0x22, 0x61, 0x02, 0x07, 0x44, 0x50, 0x3c,
	0xe9, 0x06, 0x34, 0x23, 0x5d, 0x3c, 0x60, 0xf1, 0x48, 0x7d, 0x77, 0x3f, 0x00, 0xac, 0xf9, 0x72,
	0xc2, 0x1d, 0xe5, 0x31, 0x15, 0xe6, 0x31, 0xac, 0x08, 0x99, 0x59, 0xa0, 0x0d, 0x3a, 0x3b, 0x5e,
	0xa3, 0xc8, 0x9d, 0xfa, 0x94, 0x24, 0xc3, 0x0b, 0x57, 0xd5, 0x5d, 0x5f, 0x0b, 0xcc, 0x17, 0x00,
	0xab, 0xca, 0xbd, 0x9f, 0x32, 0x36, 0xb4, 0xb6, 0xda, 0xdb, 0x9d, 0xea, 0xd9, 0x01, 0x52, 0x96,
	0x68, 0x65, 0x89, 0xb4, 0x25, 0xba, 0x62, 0xf1, 0xc8, 0xbb, 0x99, 0xe5, 0x8e, 0x51, 0xe4, 0x8e,
	0xa9, 0xe6, 0x95, 0x7a, 0xdd, 0xb7, 0x2f, 0xa7, 0x13, 0xc5, 0xd9, 0xc3, 0x38, 0x40, 0x03, 0x96,
	0x60, 0xbd, 0xb5, 0x0a, 0xa7, 0x22, 0x7c, 0xc4, 0xd9, 0x34, 0xa5, 0x42, 0x8e, 0x11, 0x3e, 0x54,
	0x9d, 0xbd, 0x55, 0xe3, 0x3b, 0x80, 0x95, 0x9e, 0x04, 0x64, 0xde, 0xc2, 0x06, 0x9d, 0x90, 0xe1,
	0x98, 0x64, 0x8c, 0xf7, 0x49, 0x18, 0x72, 0x2a, 0xd4, 0x15, 0xbb, 0xde, 0x61, 0x91, 0x3b, 0x96,
	0x72, 0xfd, 0x23, 0x71, 0xfd, 0xbd, 0x4d, 0xed, 0x52, 0x95, 0xcc, 0x10, 0xd6, 0xf5, 0x76, 0x1a,
	0x86, 0xba, 0xed, 0x08, 0xfd, 0x43, 0x1f, 0x95, 0x19, 0x7a, 0x56, 0x91, 0x3b, 0xcd, 0x5f, 0x37,
	0xae, 0xd1, 0xd5, 0x78, 0x59, 0x77, 0x3d, 0x5b, 0xd8, 0x60, 0xbe, 0xb0, 0xc1, 0xf7, 0xc2, 0x06,
	0xaf, 0x4b, 0xdb, 0x98, 0x2f, 0x6d, 0xe3, 0x73, 0x69, 0x1b, 0xf7, 0x27, 0x25, 0x16, 0xda, 0x6a,
	0x13, 0x9f, 0xf1, 0xfa, 0x61, 0x48, 0x26, 0x41, 0x45, 0xfe, 0xc9, 0xf3, 0x9f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x1b, 0x3a, 0x4b, 0xa5, 0x30, 0x02, 0x00, 0x00,
}

func (m *RewardSeries) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RewardSeries) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RewardSeries) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RewardPool) > 0 {
		for iNdEx := len(m.RewardPool) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RewardPool[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Series != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.Series))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RewardSeries) > 0 {
		for iNdEx := len(m.RewardSeries) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RewardSeries[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.EvaluatorAddress) > 0 {
		i -= len(m.EvaluatorAddress)
		copy(dAtA[i:], m.EvaluatorAddress)
		i = encodeVarintParams(dAtA, i, uint64(len(m.EvaluatorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *RewardSeries) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Series != 0 {
		n += 1 + sovParams(uint64(m.Series))
	}
	if len(m.RewardPool) > 0 {
		for _, e := range m.RewardPool {
			l = e.Size()
			n += 1 + l + sovParams(uint64(l))
		}
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.EvaluatorAddress)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if len(m.RewardSeries) > 0 {
		for _, e := range m.RewardSeries {
			l = e.Size()
			n += 1 + l + sovParams(uint64(l))
		}
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *RewardSeries) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RewardSeries: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RewardSeries: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Series", wireType)
			}
			m.Series = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Series |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardPool", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewardPool = append(m.RewardPool, types.Coin{})
			if err := m.RewardPool[len(m.RewardPool)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EvaluatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EvaluatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardSeries", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewardSeries = append(m.RewardSeries, &RewardSeries{})
			if err := m.RewardSeries[len(m.RewardSeries)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
