// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rewards/rewards.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// a map from recipient to all her rewards
type Reward struct {
	Recipient string             `protobuf:"bytes,1,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Rewards   []*RecipientReward `protobuf:"bytes,2,rep,name=rewards,proto3" json:"rewards,omitempty"`
}

func (m *Reward) Reset()         { *m = Reward{} }
func (m *Reward) String() string { return proto.CompactTextString(m) }
func (*Reward) ProtoMessage()    {}
func (*Reward) Descriptor() ([]byte, []int) {
	return fileDescriptor_35285a44c4c54379, []int{0}
}
func (m *Reward) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Reward) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Reward.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Reward) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reward.Merge(m, src)
}
func (m *Reward) XXX_Size() int {
	return m.Size()
}
func (m *Reward) XXX_DiscardUnknown() {
	xxx_messageInfo_Reward.DiscardUnknown(m)
}

var xxx_messageInfo_Reward proto.InternalMessageInfo

func (m *Reward) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

func (m *Reward) GetRewards() []*RecipientReward {
	if m != nil {
		return m.Rewards
	}
	return nil
}

type RecipientReward struct {
	Series                 Series     `protobuf:"varint,1,opt,name=series,proto3,enum=gitopia.gitopia.rewards.Series" json:"series,omitempty"`
	Amount                 types.Coin `protobuf:"bytes,2,opt,name=amount,proto3,castkey=github.com/cosmos/cosmos-sdk/types.Coin" json:"amount"`
	Creator                string     `protobuf:"bytes,3,opt,name=creator,proto3" json:"creator,omitempty"`
	ClaimedAmount          types.Coin `protobuf:"bytes,4,opt,name=claimed_amount,json=claimedAmount,proto3,castkey=github.com/cosmos/cosmos-sdk/types.Coin" json:"claimed_amount"`
	ClaimedAmountWithDecay types.Coin `protobuf:"bytes,5,opt,name=claimed_amount_with_decay,json=claimedAmountWithDecay,proto3,castkey=github.com/cosmos/cosmos-sdk/types.Coin" json:"claimed_amount_with_decay"`
}

func (m *RecipientReward) Reset()         { *m = RecipientReward{} }
func (m *RecipientReward) String() string { return proto.CompactTextString(m) }
func (*RecipientReward) ProtoMessage()    {}
func (*RecipientReward) Descriptor() ([]byte, []int) {
	return fileDescriptor_35285a44c4c54379, []int{1}
}
func (m *RecipientReward) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RecipientReward) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RecipientReward.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RecipientReward) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecipientReward.Merge(m, src)
}
func (m *RecipientReward) XXX_Size() int {
	return m.Size()
}
func (m *RecipientReward) XXX_DiscardUnknown() {
	xxx_messageInfo_RecipientReward.DiscardUnknown(m)
}

var xxx_messageInfo_RecipientReward proto.InternalMessageInfo

func (m *RecipientReward) GetSeries() Series {
	if m != nil {
		return m.Series
	}
	return Series_NONE
}

func (m *RecipientReward) GetAmount() types.Coin {
	if m != nil {
		return m.Amount
	}
	return types.Coin{}
}

func (m *RecipientReward) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *RecipientReward) GetClaimedAmount() types.Coin {
	if m != nil {
		return m.ClaimedAmount
	}
	return types.Coin{}
}

func (m *RecipientReward) GetClaimedAmountWithDecay() types.Coin {
	if m != nil {
		return m.ClaimedAmountWithDecay
	}
	return types.Coin{}
}

func init() {
	proto.RegisterType((*Reward)(nil), "gitopia.gitopia.rewards.Reward")
	proto.RegisterType((*RecipientReward)(nil), "gitopia.gitopia.rewards.RecipientReward")
}

func init() { proto.RegisterFile("rewards/rewards.proto", fileDescriptor_35285a44c4c54379) }

var fileDescriptor_35285a44c4c54379 = []byte{
	// 377 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0xbf, 0x4f, 0xfa, 0x40,
	0x14, 0x6f, 0xe1, 0xfb, 0x2d, 0xe1, 0x88, 0x98, 0x5c, 0xfc, 0x51, 0x88, 0x29, 0x84, 0xc5, 0x2e,
	0xdc, 0x05, 0x18, 0x9c, 0x45, 0x13, 0xf7, 0x3a, 0x98, 0xb8, 0x90, 0x6b, 0x7b, 0x29, 0xa7, 0xb4,
	0x57, 0x7b, 0x07, 0xc8, 0x6a, 0xe2, 0xee, 0xff, 0xe4, 0xc2, 0xc8, 0xe8, 0xa4, 0x06, 0xfe, 0x11,
	0x43, 0x7b, 0x55, 0x31, 0x61, 0x63, 0x7a, 0xed, 0xbd, 0xcf, 0xaf, 0x77, 0xf7, 0xc0, 0x61, 0x42,
	0xa7, 0x24, 0xf1, 0x05, 0x56, 0x15, 0xc5, 0x09, 0x97, 0x1c, 0x1e, 0x07, 0x4c, 0xf2, 0x98, 0x11,
	0x94, 0x57, 0xd5, 0xae, 0x1f, 0x04, 0x3c, 0xe0, 0x29, 0x06, 0xaf, 0xbf, 0x32, 0x78, 0x1d, 0xe6,
	0x2a, 0x31, 0xe7, 0x23, 0x75, 0x66, 0x79, 0x5c, 0x84, 0x5c, 0x60, 0x97, 0x08, 0x8a, 0x27, 0x1d,
	0x97, 0x4a, 0xd2, 0xc1, 0x1e, 0x67, 0x51, 0xd6, 0x6f, 0xdd, 0x01, 0xc3, 0x49, 0x59, 0xf0, 0x04,
	0x94, 0x13, 0xea, 0xb1, 0x98, 0xd1, 0x48, 0x9a, 0x7a, 0x53, 0xb7, 0xcb, 0xce, 0xcf, 0x01, 0xec,
	0x83, 0x92, 0x52, 0x37, 0x0b, 0xcd, 0xa2, 0x5d, 0xe9, 0xda, 0x68, 0x4b, 0x38, 0xe4, 0xe4, 0xa4,
	0x4c, 0xd8, 0xc9, 0x89, 0xad, 0xd7, 0x22, 0xd8, 0xff, 0xd3, 0x84, 0x67, 0xc0, 0x10, 0x34, 0x61,
	0x54, 0xa4, 0x96, 0xd5, 0x6e, 0x63, 0xab, 0xec, 0x75, 0x0a, 0x73, 0x14, 0x1c, 0xba, 0xc0, 0x20,
	0x21, 0x1f, 0x47, 0xd2, 0x2c, 0x34, 0x75, 0xbb, 0xd2, 0xad, 0xa1, 0x6c, 0x52, 0xb4, 0x9e, 0x14,
	0xa9, 0x49, 0xd1, 0x05, 0x67, 0x51, 0x1f, 0xcf, 0xdf, 0x1b, 0xda, 0xd3, 0x47, 0xe3, 0x34, 0x60,
	0x72, 0x38, 0x76, 0x91, 0xc7, 0x43, 0xac, 0xae, 0x25, 0x2b, 0x6d, 0xe1, 0xdf, 0x63, 0x39, 0x8b,
	0xa9, 0x48, 0x09, 0x8e, 0x52, 0x86, 0x26, 0x28, 0x79, 0x09, 0x25, 0x92, 0x27, 0x66, 0x31, 0xbd,
	0x90, 0xfc, 0x17, 0x3e, 0x80, 0xaa, 0x37, 0x22, 0x2c, 0xa4, 0xfe, 0x40, 0xa5, 0xf8, 0xb7, 0xf3,
	0x14, 0x7b, 0xca, 0xe1, 0x3c, 0x0b, 0xf3, 0xac, 0x83, 0xda, 0xa6, 0xe7, 0x60, 0xca, 0xe4, 0x70,
	0xe0, 0x53, 0x8f, 0xcc, 0xcc, 0xff, 0x3b, 0xb7, 0x3f, 0xda, 0xb0, 0xbf, 0x61, 0x72, 0x78, 0xb9,
	0x76, 0xea, 0x5f, 0xcd, 0x97, 0x96, 0xbe, 0x58, 0x5a, 0xfa, 0xe7, 0xd2, 0xd2, 0x5f, 0x56, 0x96,
	0xb6, 0x58, 0x59, 0xda, 0xdb, 0xca, 0xd2, 0x6e, 0xdb, 0xbf, 0xa4, 0xd5, 0xeb, 0x7d, 0xd7, 0x49,
	0x0f, 0x3f, 0xe6, 0xdb, 0x9d, 0xb9, 0xb8, 0x46, 0xba, 0x81, 0xbd, 0xaf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x5a, 0x83, 0xef, 0x82, 0xfd, 0x02, 0x00, 0x00,
}

func (m *Reward) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Reward) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Reward) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Rewards) > 0 {
		for iNdEx := len(m.Rewards) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Rewards[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintRewards(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Recipient) > 0 {
		i -= len(m.Recipient)
		copy(dAtA[i:], m.Recipient)
		i = encodeVarintRewards(dAtA, i, uint64(len(m.Recipient)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RecipientReward) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RecipientReward) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RecipientReward) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.ClaimedAmountWithDecay.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintRewards(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size, err := m.ClaimedAmount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintRewards(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintRewards(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x1a
	}
	{
		size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintRewards(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.Series != 0 {
		i = encodeVarintRewards(dAtA, i, uint64(m.Series))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintRewards(dAtA []byte, offset int, v uint64) int {
	offset -= sovRewards(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Reward) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Recipient)
	if l > 0 {
		n += 1 + l + sovRewards(uint64(l))
	}
	if len(m.Rewards) > 0 {
		for _, e := range m.Rewards {
			l = e.Size()
			n += 1 + l + sovRewards(uint64(l))
		}
	}
	return n
}

func (m *RecipientReward) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Series != 0 {
		n += 1 + sovRewards(uint64(m.Series))
	}
	l = m.Amount.Size()
	n += 1 + l + sovRewards(uint64(l))
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovRewards(uint64(l))
	}
	l = m.ClaimedAmount.Size()
	n += 1 + l + sovRewards(uint64(l))
	l = m.ClaimedAmountWithDecay.Size()
	n += 1 + l + sovRewards(uint64(l))
	return n
}

func sovRewards(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozRewards(x uint64) (n int) {
	return sovRewards(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Reward) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRewards
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Reward: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Reward: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recipient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRewards
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRewards
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Recipient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rewards", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRewards
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRewards
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Rewards = append(m.Rewards, &RecipientReward{})
			if err := m.Rewards[len(m.Rewards)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRewards(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRewards
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RecipientReward) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRewards
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RecipientReward: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RecipientReward: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Series", wireType)
			}
			m.Series = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Series |= Series(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRewards
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRewards
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRewards
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRewards
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClaimedAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRewards
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRewards
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ClaimedAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClaimedAmountWithDecay", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRewards
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRewards
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ClaimedAmountWithDecay.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRewards(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRewards
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipRewards(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowRewards
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthRewards
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupRewards
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthRewards
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthRewards        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowRewards          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupRewards = fmt.Errorf("proto: unexpected end of group")
)
