syntax = "proto3";
package gitopia.gitopia.storage;

import "google/protobuf/timestamp.proto";
import "gogoproto/gogo.proto";
import "cosmos/base/v1beta1/coin.proto";
import "amino/amino.proto";
import "gitopia/gitopia/storage/types.proto";

option go_package = "github.com/gitopia/gitopia/v6/x/storage/types";

// EventProviderRegistered is emitted when a provider is registered
message EventProviderRegistered {
  string address = 1;
  string peer_id = 2;
}

// EventProviderStatusUpdated is emitted when provider status is updated
message EventProviderStatusUpdated {
  string address = 1;
  bool online = 2;
}

// EventPackfileUpdated is emitted when a packfile is updated
message EventPackfileUpdated {
  uint64 repository_id = 1;
  string new_cid = 2;
  string old_cid = 3;
  string new_name = 4;
  string old_name = 5;
  string provider = 6;
  bool deleted = 7;
}

// EventReleaseAssetsUpdated is emitted when release assets are updated
message EventReleaseAssetsUpdated {
  uint64 repository_id = 1;
  string tag = 2;
  repeated ReleaseAssetUpdate assets = 3;
  string provider = 4;
}

// EventChallengeCreated is emitted when a new challenge is created
message EventChallengeCreated {
  uint64 challenge_id = 1;
  string provider = 2;
}

// EventChallengeCompleted is emitted when a challenge is completed
message EventChallengeCompleted {
  uint64 challenge_id = 1;
  string provider = 2;
  bool success = 3;
}

// EventProviderUnregistered is emitted when a provider initiates unregistration
message EventProviderUnregistered {
  string address = 1;
  google.protobuf.Timestamp unstake_completion_time = 2 [
    (gogoproto.nullable) = false,
    (gogoproto.stdtime) = true
  ];
}

// EventProviderUnstakeCompleted is emitted when a provider's unstaking is completed
message EventProviderUnstakeCompleted {
  string address = 1;
  repeated cosmos.base.v1beta1.Coin amount = 2 [
    (gogoproto.castrepeated) = "github.com/cosmos/cosmos-sdk/types.Coins",
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
}

// EventLFSObjectUpdated is emitted when an LFS object is updated
message EventLFSObjectUpdated {
  uint64 repository_id = 1;
  string oid = 2;
  string cid = 3;
  string provider = 4;
  bool deleted = 5;
}

// EventDeleteStorageObject is emitted when older storage objects are deleted
message EventDeleteStorageObject {
  repeated string cids = 1;
  uint64 repository_id = 2;
  string provider = 3;
}

// EventRepositoryDeleted is emitted when a repository is deleted
message EventRepositoryDeleted {
  uint64 repository_id = 1;
  string provider = 2;
  Packfile packfile = 3;
  repeated ReleaseAsset release_assets = 4;
  repeated LFSObject lfs_objects = 5;
}
